-- What the catalog starts with: the game, its four catalogs, the sources suggestions come
-- from, and the word lists. The words and terms are what today's TCGdex-built catalog
-- already uses, tidied: one spelling for "Holo Rare" and "Rare Holo", World Championships
-- player signatures left out until those decks are decided on, and the two words TCGdex
-- uses for both a stamp and a foil (pokeball, professor-program) given one meaning each.
-- Everything here is a starting point to be corrected in the editor, not a finished list.

insert into games (id, name) values ('ptcg', 'Pokémon TCG');

insert into catalogs (game_id, language, name, native_name, sort) values
  ('ptcg', 'en', 'English', 'English', 1),
  ('ptcg', 'jp', 'Japanese', '日本語', 2),
  ('ptcg', 'cht', 'Traditional Chinese', '繁體中文', 3),
  ('ptcg', 'chs', 'Simplified Chinese', '简体中文', 4);

insert into sources (id, name, url, terms) values
  ('tcgdex', 'TCGdex', 'https://tcgdex.dev',
   'Card data is MIT-licensed (github.com/tcgdex/cards-database). Card images belong to The Pokémon Company.'),
  ('pokemontcg-io', 'Pokémon TCG API', 'https://pokemontcg.io', null),
  ('tcgplayer', 'TCGplayer', 'https://www.tcgplayer.com',
   'Product data and photos, read through tcgcsv.com no more than once a day.'),
  ('upload', 'Your own files', null, null),
  ('pocketful-2026', 'Pocketful catalog, 2026-09-13', 'https://github.com/TronVonDoom/Pocketful-Catalog',
   'The TCGdex-built catalog as it stood before this database, with its corrections, pictures and TCGplayer links.');

insert into variant_words (word, kind, label, sort) values
  ('normal', 'finish', 'Normal', 1),
  ('holo', 'finish', 'Holo', 2),
  ('reverse', 'finish', 'Reverse Holo', 3),
  ('lenticular', 'finish', 'Lenticular', 4),
  ('metal', 'finish', 'Metal', 5),
  ('1st-edition', 'edition', '1st Edition', 1),
  ('shadowless', 'edition', 'Shadowless', 2),
  ('1999-2000-copyright', 'edition', '1999-2000 Copyright', 3),
  ('1999-copyright', 'edition', '1999 Copyright', 4),
  ('no-e-reader', 'edition', 'No e-Reader', 5),
  ('blue-border', 'edition', 'Blue Border', 6),
  ('gold-border', 'edition', 'Gold Border', 7),
  ('glossy', 'edition', 'Glossy', 8),
  ('peelable-ditto', 'edition', 'Peelable Ditto', 9),
  ('cosmos', 'pattern', 'Cosmos Holo', 0),
  ('cracked-ice', 'pattern', 'Cracked Ice Holo', 0),
  ('duskball', 'pattern', 'Dusk Ball Pattern', 0),
  ('energy', 'pattern', 'Energy Pattern', 0),
  ('friendball', 'pattern', 'Friend Ball Pattern', 0),
  ('galaxy', 'pattern', 'Galaxy Holo', 0),
  ('gold', 'pattern', 'Gold', 0),
  ('league', 'pattern', 'League', 0),
  ('loveball', 'pattern', 'Love Ball Pattern', 0),
  ('masterball', 'pattern', 'Master Ball Pattern', 0),
  ('mirror', 'pattern', 'Mirror Holo', 0),
  ('player-reward', 'pattern', 'Player Rewards', 0),
  ('pokeball', 'pattern', 'Poké Ball Pattern', 0),
  ('professor-program-foil', 'pattern', 'Professor Program Foil', 0),
  ('quickball', 'pattern', 'Quick Ball Pattern', 0),
  ('rainbow', 'pattern', 'Rainbow', 0),
  ('starlight', 'pattern', 'Starlight Holo', 0),
  ('team-rocket', 'pattern', 'Team Rocket Pattern', 0),
  ('tinsel', 'pattern', 'Tinsel Holo', 0),
  ('10th-anniversary', 'stamp', '10th Anniversary', 0),
  ('1st-movie', 'stamp', '1st Movie', 0),
  ('1st-movie-inverted', 'stamp', '1st Movie Inverted', 0),
  ('25th-celebration', 'stamp', '25th Celebration', 0),
  ('30th-pokeday', 'stamp', '30th Pokémon Day', 0),
  ('ace-trainer', 'stamp', 'Ace Trainer', 0),
  ('asia-2023-24', 'stamp', 'Asia 2023-24', 0),
  ('asia-promo', 'stamp', 'Asia Promo', 0),
  ('bulbasaur', 'stamp', 'Bulbasaur', 0),
  ('champion', 'stamp', 'Champion', 0),
  ('charmander', 'stamp', 'Charmander', 0),
  ('chicago-2009', 'stamp', 'Chicago 2009', 0),
  ('city-championships', 'stamp', 'City Championships', 0),
  ('comic-con', 'stamp', 'Comic-Con', 0),
  ('countdown-calendar', 'stamp', 'Countdown Calendar Stamp', 0),
  ('destiny-deoxys', 'stamp', 'Destiny Deoxys', 0),
  ('distributor-meeting', 'stamp', 'Distributor Meeting', 0),
  ('eb-games', 'stamp', 'EB Games Stamp', 0),
  ('finalist', 'stamp', 'Finalist', 0),
  ('fossil-museum', 'stamp', 'Fossil Museum', 0),
  ('games-expo', 'stamp', 'Games Expo', 0),
  ('gamestop', 'stamp', 'GameStop Stamp', 0),
  ('gen-con', 'stamp', 'Gen Con', 0),
  ('grey-star', 'stamp', 'Grey Star', 0),
  ('gym-challenge', 'stamp', 'Gym Challenge', 0),
  ('horizons', 'stamp', 'Horizons', 0),
  ('illustration-contest-2022', 'stamp', 'Illustration Contest 2022', 0),
  ('illustration-contest-2024', 'stamp', 'Illustration Contest 2024', 0),
  ('inquest-gamer', 'stamp', 'InQuest Gamer', 0),
  ('international-championship-europe', 'stamp', 'Europe International Championships', 0),
  ('international-championship-latin-america', 'stamp', 'Latin America International Championships', 0),
  ('international-championship-north-america', 'stamp', 'North America International Championships', 0),
  ('jr-stamp-rally', 'stamp', 'Jr. Stamp Rally', 0),
  ('judge', 'stamp', 'Judge Stamp', 0),
  ('kraze-club', 'stamp', 'Kraze Club', 0),
  ('master-ball-league', 'stamp', 'Master Ball League', 0),
  ('mcdonalds', 'stamp', 'McDonald''s Stamp', 0),
  ('national-championships', 'stamp', 'National Championships', 0),
  ('nintendo-world', 'stamp', 'Nintendo World', 0),
  ('origins', 'stamp', 'Origins', 0),
  ('origins-2008', 'stamp', 'Origins 2008', 0),
  ('pikachu', 'stamp', 'Pikachu', 0),
  ('pikachu-tail', 'stamp', 'Pikachu Tail', 0),
  ('platinum', 'stamp', 'Platinum', 0),
  ('player-rewards-program', 'stamp', 'Player Rewards', 0),
  ('poke-ball-league', 'stamp', 'Poké Ball League', 0),
  ('pokeball-stamp', 'stamp', 'Poké Ball Stamp', 0),
  ('pokemon-4-ever', 'stamp', 'Pokémon 4Ever', 0),
  ('pokemon-center', 'stamp', 'Pokémon Center Stamp', 0),
  ('pokemon-center-ny', 'stamp', 'Pokémon Center NY Stamp', 0),
  ('pokemon-day', 'stamp', 'Pokémon Day Stamp', 0),
  ('pokemon-rocks-america', 'stamp', 'Pokémon Rocks America', 0),
  ('pokemon-together', 'stamp', 'Pokémon Together', 0),
  ('poketour-99', 'stamp', 'PokéTour ''99', 0),
  ('pop-tournament', 'stamp', 'POP Tournament', 0),
  ('pre-release', 'stamp', 'Prerelease Stamp', 0),
  ('professor-program', 'stamp', 'Professor Program', 0),
  ('quarter-finalist', 'stamp', 'Quarter-Finalist', 0),
  ('rain-city', 'stamp', 'Rain City', 0),
  ('regional-championships', 'stamp', 'Regional Championships', 0),
  ('scrye', 'stamp', 'Scrye', 0),
  ('semi-finalist', 'stamp', 'Semi-Finalist', 0),
  ('set-logo', 'stamp', 'Set Logo Stamp', 0),
  ('snowflake', 'stamp', 'Snowflake Stamp', 0),
  ('squirtle', 'stamp', 'Squirtle', 0),
  ('stadium-challenge', 'stamp', 'Stadium Challenge', 0),
  ('staff', 'stamp', 'Staff Stamp', 0),
  ('state-championships', 'stamp', 'State Championships', 0),
  ('thank-you', 'stamp', 'Thank You Stamp', 0),
  ('top-eight', 'stamp', 'Top 8', 0),
  ('top-sixteen', 'stamp', 'Top 16', 0),
  ('top-thirty-two', 'stamp', 'Top 32', 0),
  ('trick-or-trade', 'stamp', 'Trick or Trade Stamp', 0),
  ('ultra-ball-league', 'stamp', 'Ultra Ball League', 0),
  ('w-promo', 'stamp', 'W Promo Stamp', 0),
  ('winner', 'stamp', 'Winner Stamp', 0),
  ('wizard-world-chicago', 'stamp', 'Wizard World Chicago', 0),
  ('wizard-world-philadelphia', 'stamp', 'Wizard World Philadelphia', 0),
  ('worlds-2004', 'stamp', 'Worlds 2004', 0),
  ('worlds-2005', 'stamp', 'Worlds 2005', 0),
  ('worlds-2007', 'stamp', 'Worlds 2007', 0),
  ('worlds-2008', 'stamp', 'Worlds 2008', 0),
  ('worlds-2009', 'stamp', 'Worlds 2009', 0),
  ('worlds-2010', 'stamp', 'Worlds 2010', 0),
  ('worlds-2022', 'stamp', 'Worlds 2022', 0),
  ('worlds-2023', 'stamp', 'Worlds 2023', 0),
  ('worlds-2024', 'stamp', 'Worlds 2024', 0),
  ('worlds-2025', 'stamp', 'Worlds 2025', 0),
  ('wotc', 'stamp', 'WotC', 0),
  ('1st-edition-error', 'error', '1st Edition Error', 0),
  ('1st-edition-scratch-error', 'error', '1st Edition Scratch Error', 0),
  ('d-edition-error', 'error', 'D Edition Error', 0),
  ('red-cheeks', 'error', 'Red Cheeks', 0),
  ('missing-expansion-symbol', 'error', 'Missing Expansion Symbol', 0),
  ('aoki-error', 'error', 'Aoki Error', 0),
  ('no-holo-error', 'error', 'No Holo Error', 0),
  ('phanphy-error', 'error', 'Phanphy Error', 0),
  ('japanese-back', 'error', 'Japanese Back', 0),
  ('rarity-error', 'error', 'Rarity Error', 0),
  ('evolution-box-error', 'error', 'Evolution Box Error', 0),
  ('d-ink-dot-error', 'error', 'D Ink Dot Error', 0),
  ('missing-hp', 'error', 'Missing HP', 0),
  ('missing-retreat-cost', 'error', 'Missing Retreat Cost', 0),
  ('energy-symbol-error', 'error', 'Energy Symbol Error', 0),
  ('text-error', 'error', 'Text Error', 0),
  ('shifted-energy-cost', 'error', 'Shifted Energy Cost', 0);

insert into terms (kind, code, labels, sort) values
  ('type', 'grass', jsonb_build_object('en', 'Grass'), 1),
  ('type', 'fire', jsonb_build_object('en', 'Fire'), 2),
  ('type', 'water', jsonb_build_object('en', 'Water'), 3),
  ('type', 'lightning', jsonb_build_object('en', 'Lightning'), 4),
  ('type', 'psychic', jsonb_build_object('en', 'Psychic'), 5),
  ('type', 'fighting', jsonb_build_object('en', 'Fighting'), 6),
  ('type', 'darkness', jsonb_build_object('en', 'Darkness'), 7),
  ('type', 'metal', jsonb_build_object('en', 'Metal'), 8),
  ('type', 'fairy', jsonb_build_object('en', 'Fairy'), 9),
  ('type', 'dragon', jsonb_build_object('en', 'Dragon'), 10),
  ('type', 'colorless', jsonb_build_object('en', 'Colorless'), 11),
  ('rarity', 'common', jsonb_build_object('en', 'Common'), 1),
  ('rarity', 'uncommon', jsonb_build_object('en', 'Uncommon'), 2),
  ('rarity', 'rare', jsonb_build_object('en', 'Rare'), 3),
  ('rarity', 'holo-rare', jsonb_build_object('en', 'Holo Rare'), 4),
  ('rarity', 'promo', jsonb_build_object('en', 'Promo'), 5),
  ('rarity', 'holo-rare-lv-x', jsonb_build_object('en', 'Holo Rare LV.X'), 6),
  ('rarity', 'rare-prime', jsonb_build_object('en', 'Rare Prime'), 7),
  ('rarity', 'legend', jsonb_build_object('en', 'LEGEND'), 8),
  ('rarity', 'holo-rare-v', jsonb_build_object('en', 'Holo Rare V'), 9),
  ('rarity', 'holo-rare-vmax', jsonb_build_object('en', 'Holo Rare VMAX'), 10),
  ('rarity', 'holo-rare-vstar', jsonb_build_object('en', 'Holo Rare VSTAR'), 11),
  ('rarity', 'amazing-rare', jsonb_build_object('en', 'Amazing Rare'), 12),
  ('rarity', 'radiant-rare', jsonb_build_object('en', 'Radiant Rare'), 13),
  ('rarity', 'shiny-rare', jsonb_build_object('en', 'Shiny Rare'), 14),
  ('rarity', 'shiny-rare-v', jsonb_build_object('en', 'Shiny Rare V'), 15),
  ('rarity', 'shiny-rare-vmax', jsonb_build_object('en', 'Shiny Rare VMAX'), 16),
  ('rarity', 'shiny-ultra-rare', jsonb_build_object('en', 'Shiny Ultra Rare'), 17),
  ('rarity', 'double-rare', jsonb_build_object('en', 'Double Rare'), 18),
  ('rarity', 'ultra-rare', jsonb_build_object('en', 'Ultra Rare'), 19),
  ('rarity', 'illustration-rare', jsonb_build_object('en', 'Illustration Rare'), 20),
  ('rarity', 'special-illustration-rare', jsonb_build_object('en', 'Special Illustration Rare'), 21),
  ('rarity', 'hyper-rare', jsonb_build_object('en', 'Hyper Rare'), 22),
  ('rarity', 'mega-hyper-rare', jsonb_build_object('en', 'Mega Hyper Rare'), 23),
  ('rarity', 'secret-rare', jsonb_build_object('en', 'Secret Rare'), 24),
  ('rarity', 'ace-spec-rare', jsonb_build_object('en', 'ACE SPEC Rare'), 25),
  ('rarity', 'black-white-rare', jsonb_build_object('en', 'Black White Rare'), 26),
  ('rarity', 'classic-collection', jsonb_build_object('en', 'Classic Collection'), 27),
  ('rarity', 'full-art-trainer', jsonb_build_object('en', 'Full Art Trainer'), 28),
  ('subtype', 'basic', jsonb_build_object('en', 'Basic'), 1),
  ('subtype', 'stage-1', jsonb_build_object('en', 'Stage 1'), 2),
  ('subtype', 'stage-2', jsonb_build_object('en', 'Stage 2'), 3),
  ('subtype', 'baby', jsonb_build_object('en', 'Baby'), 4),
  ('subtype', 'restored', jsonb_build_object('en', 'Restored'), 5),
  ('subtype', 'level-up', jsonb_build_object('en', 'Level-Up'), 6),
  ('subtype', 'break', jsonb_build_object('en', 'BREAK'), 7),
  ('subtype', 'mega', jsonb_build_object('en', 'Mega'), 8),
  ('subtype', 'vmax', jsonb_build_object('en', 'VMAX'), 9),
  ('subtype', 'vstar', jsonb_build_object('en', 'VSTAR'), 10),
  ('subtype', 'v-union', jsonb_build_object('en', 'V-UNION'), 11),
  ('subtype', 'item', jsonb_build_object('en', 'Item'), 12),
  ('subtype', 'supporter', jsonb_build_object('en', 'Supporter'), 13),
  ('subtype', 'pokemon-tool', jsonb_build_object('en', 'Pokémon Tool'), 14),
  ('subtype', 'stadium', jsonb_build_object('en', 'Stadium'), 15),
  ('subtype', 'technical-machine', jsonb_build_object('en', 'Technical Machine'), 16),
  ('subtype', 'rockets-secret-machine', jsonb_build_object('en', 'Rocket''s Secret Machine'), 17),
  ('subtype', 'basic-energy', jsonb_build_object('en', 'Basic Energy'), 18),
  ('subtype', 'special-energy', jsonb_build_object('en', 'Special Energy'), 19),
  ('subtype', 'ex', jsonb_build_object('en', 'ex'), 20),
  ('subtype', 'ex-uppercase', jsonb_build_object('en', 'EX'), 21),
  ('subtype', 'gx', jsonb_build_object('en', 'GX'), 22),
  ('subtype', 'tag-team-gx', jsonb_build_object('en', 'TAG TEAM-GX'), 23),
  ('subtype', 'v', jsonb_build_object('en', 'V'), 24),
  ('subtype', 'sp', jsonb_build_object('en', 'SP'), 25),
  ('subtype', 'prime', jsonb_build_object('en', 'Prime'), 26),
  ('subtype', 'legend', jsonb_build_object('en', 'LEGEND'), 27),
  ('ability_kind', 'ability', jsonb_build_object('en', 'Ability'), 1),
  ('ability_kind', 'poke-power', jsonb_build_object('en', 'Poké-Power'), 2),
  ('ability_kind', 'poke-body', jsonb_build_object('en', 'Poké-Body'), 3),
  ('ability_kind', 'pokemon-power', jsonb_build_object('en', 'Pokémon Power'), 4),
  ('ability_kind', 'ancient-trait', jsonb_build_object('en', 'Ancient Trait'), 5);
